name: Email New Readwise Highlights

on:
  pull_request:
    branches:
      - main

jobs:
  email-results:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      READWISE_API_KEY: ${{ secrets.READWISE_API_KEY }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          npm install

      - name: Send email
        run: node ./export.js
